# -*- coding: utf-8 -*-
# Muzayede Faz 4: Wikipedia "en pahali tablolar" liste makalelerinden (List of
# most expensive paintings + ...by living artists) uretildi. Faz 3'ten farkli
# olarak fiyat zaten kaynakli (liste makalesinin kendi tablosundan), ajan sadece
# ressam_id eslesmesi (mevcut ressamsa AYNI id'yi tekrar kullanir - bkz.
# tablo_id/ressam_id ayrimi, veri/muzayede_uret.py) + gorsel + risk_seviyesi icin
# kullanildi. 87 ham adaydan (dahili tekrarlar temizlendikten sonra) 82'si
# islendi, 64'u onaylandi (37'si zaten var olan ressamlarin YENI tablosu, 27'si
# tamamen yeni ressam). Elenenler: 2 "zaten mevcut" (dedup), 4 "ressam degil"
# (heykel/enstalasyon - Koons, Hirst), 9 "gorsel bulunamadi", 1 dahili tekrar
# (Jasper Johns "False Start" iki farkli satis yilinda listelenmisti, 2006
# satisi tutuldu), 1 (Correggio "Magdalen in the Desert") 1945'te yok edilmis,
# guvenilir gorsel bulunamadigi icin manuel cikarildi.
# Alan sirasi ana DATA ile ayni: ressam_id, isim, dogum_olum, ulke, akim,
# risk_seviyesi, tablo_adi, tablo_yili, gorsel_url, fiyat_usd, satis_yili,
# muzayede_evi, kaynak_url

FAZ4_DATA = [
    ('gustav-klimt', 'Gustav Klimt', '1862-1918', 'Avusturya', 'Sembolizm', 'public_domain', 'Wasserschlangen II (Water Serpents II)', '1904-1907', 'https://upload.wikimedia.org/wikipedia/commons/8/87/Klimt%2C_Wasserschlangen_II.jpg', 183800000, 2013, 'Private sale', 'https://en.wikipedia.org/wiki/List_of_most_expensive_paintings'),
    ('rembrandt', 'Rembrandt van Rijn', '1606-1669', 'Hollanda (Felemenk Cumhuriyeti)', 'Barok (Hollanda Altın Çağı)', 'public_domain', 'The Standard Bearer (De vaandeldrager)', '1636', 'https://upload.wikimedia.org/wikipedia/commons/b/b8/Rembrandt%2C_The_Standard-Bearer%2C_1636.jpg', 198000000, 2022, 'Private sale (Rothschild ailesinden Rijksmuseum\'a)', 'https://en.wikipedia.org/wiki/List_of_most_expensive_paintings'),
    ('amedeo-modigliani', 'Amedeo Modigliani', '1884-1920', 'İtalya', 'Ecole de Paris / Ekspresyonizm', 'public_domain', 'Nu couché (sur le côté gauche)', '1917', 'https://upload.wikimedia.org/wikipedia/commons/0/03/Auf_der_Seite_liegender_Frauenakt_%28Amedeo_Modigliani%29-WUS04316.jpg', 157159000, 2018, 'Sotheby\'s, New York', 'https://en.wikipedia.org/wiki/List_of_most_expensive_paintings'),
    ('francis-bacon', 'Francis Bacon', '1909-1992', 'İrlanda/Birleşik Krallık', 'Figüratif Ekspresyonizm', 'dikkat', 'Three Studies of Lucian Freud', '1969', 'https://www.christies.com/img/LotImages/2013/NYR/2013_NYR_02791_0008A_000(francis_bacon_three_studies_of_lucian_freud).jpg', 142405000, 2013, 'Christie\'s, New York', 'https://en.wikipedia.org/wiki/Three_Studies_of_Lucian_Freud'),
    ('pablo-picasso', 'Pablo Picasso', '1881-1973', 'İspanya', 'Kübizm', 'dikkat', 'Garçon à la pipe', '1905', 'https://upload.wikimedia.org/wikipedia/en/9/9c/Gar%C3%A7on_%C3%A0_la_pipe.jpg', 104168000, 2004, 'Sotheby\'s, New York', 'https://en.wikipedia.org/wiki/List_of_most_expensive_paintings'),
    ('paul-gauguin', 'Paul Gauguin', '1848-1903', 'Fransa', 'Post-Empresyonizm', 'public_domain', 'Otahi (Seule / Alone)', '1893', 'https://upload.wikimedia.org/wikipedia/commons/b/b6/Paul_Gauguin_093.jpg', 120000000, 2013, 'Private sale (Yves Bouvier\'den Dmitry Rybolovlev\'e)', 'https://en.wikipedia.org/wiki/List_of_most_expensive_paintings'),
    ('pablo-picasso', 'Pablo Picasso', '1881-1973', 'İspanya', 'Kübizm', 'dikkat', 'Nude, Green Leaves and Bust', '1932', 'https://upload.wikimedia.org/wikipedia/en/2/2b/Nude_Green_Leaves_and_Bust_by_Picasso.jpg', 106482500, 2010, 'Christie\'s, New York', 'https://en.wikipedia.org/wiki/Nude,_Green_Leaves_and_Bust'),
    ('pablo-picasso', 'Pablo Picasso', '1881-1973', 'İspanya', 'Kübizm', 'dikkat', 'Dora Maar au Chat', '1941', 'https://uploads1.wikiart.org/00304/images/pablo-picasso/dora-maar-with-cat.jpeg!Large.jpeg', 95216000, 2006, 'Sotheby\'s, New York', 'https://en.wikipedia.org/wiki/List_of_most_expensive_paintings'),
    ('roy-lichtenstein', 'Roy Lichtenstein', '1923-1997', 'ABD', 'Pop Art', 'dikkat', 'Nurse', '1964', 'https://upload.wikimedia.org/wikipedia/en/c/c1/Nurse_%28Lichtenstein%29.png', 95365000, 2015, 'Christie\'s, New York', 'https://en.wikipedia.org/wiki/Nurse_(Lichtenstein)'),
    ('paul-gauguin', 'Paul Gauguin', '1848-1903', 'Fransa', 'Post-Empresyonizm', 'public_domain', 'Te Fare (La Maison)', '1892', 'https://upload.wikimedia.org/wikipedia/commons/b/b7/Te_Fare_%28La_maison%29_Paul_Gauguin_1892.jpg', 85000000, 2008, 'Private sale', 'https://en.wikipedia.org/wiki/List_of_most_expensive_paintings'),
    ('pablo-picasso', 'Pablo Picasso', '1881-1973', 'İspanya', 'Kübizm', 'dikkat', 'Yo, Picasso', '1901', 'https://upload.wikimedia.org/wikipedia/en/f/ff/Yo%2C_Picasso.jpg', 47850000, 1989, 'Sotheby\'s, New York', 'https://en.wikipedia.org/wiki/Yo,_Picasso'),
    ('mark-rothko', 'Mark Rothko', '1903-1970', 'ABD', 'Soyut Ekspresyonizm (Color Field)', 'dikkat', 'Orange, Red, Yellow', '1961', 'https://upload.wikimedia.org/wikipedia/en/9/97/Orange%2C_Red%2C_Yellow.jpg', 86882500, 2012, 'Christie\'s, New York', 'https://en.wikipedia.org/wiki/Orange,_Red,_Yellow'),
    ('barnett-newman', 'Barnett Newman', '1905-1970', 'ABD', 'Soyut Dışavurumculuk (Renk Alanı Resmi)', 'dikkat', 'Black Fire I', '1961', 'https://upload.wikimedia.org/wikipedia/en/7/79/Black_Fire_I.jpg', 84165000, 2014, 'Christie\'s, New York', 'https://en.wikipedia.org/wiki/List_of_most_expensive_paintings'),
    ('mark-rothko', 'Mark Rothko', '1903-1970', 'ABD (Letonya doğumlu)', 'Soyut Dışavurumculuk (Renk Alanı Resmi)', 'dikkat', 'White Center (Yellow, Pink and Lavender on Rose)', '1950', 'https://upload.wikimedia.org/wikipedia/en/9/93/White_Center_%28Yellow%2C_Pink_and_Lavender_on_Rose%29.jpg', 72840000, 2007, 'Sotheby\'s', 'https://www.sothebys.com/en/auctions/ecatalogue/2007/contemporary-art-evening-sale-n08317/lot.31.html'),
    ('andy-warhol', 'Andy Warhol', '1928-1987', 'ABD', 'Pop Art', 'dikkat', 'Triple Elvis', '1963', 'https://upload.wikimedia.org/wikipedia/en/9/98/Triple-Elvis-by-Andy-Warhol.jpg', 81925000, 2014, 'Christie\'s, New York', 'https://en.wikipedia.org/wiki/List_of_most_expensive_paintings'),
    ('andy-warhol', 'Andy Warhol', '1928-1987', 'ABD', 'Pop Art', 'dikkat', 'Green Car Crash (Green Burning Car I)', '1963', 'https://upload.wikimedia.org/wikipedia/en/0/06/Green_Car_Crash_by_Andy_Warhol_%281963%29.jpg', 71720000, 2007, 'Christie\'s', 'https://en.wikipedia.org/wiki/Green_Car_Crash'),
    ('mark-rothko', 'Mark Rothko', '1903-1970', 'Letonya doğumlu, Amerika Birleşik Devletleri', 'Soyut Ekspresyonizm (Color Field)', 'dikkat', 'No. 10', '1958', 'https://upload.wikimedia.org/wikipedia/en/d/d2/No._10_%28Rothko%29.png', 81925000, 2015, 'Christie\'s, New York', 'https://en.wikipedia.org/wiki/No._10_(Rothko)'),
    ('claude-monet', 'Claude Monet', '1840-1926', 'Fransa', 'Empresyonizm', 'public_domain', 'Nymphéas en fleur', '1914-1917', 'https://upload.wikimedia.org/wikipedia/commons/2/2c/Claude_Monet_-_Nympheas_en_fleur.jpg', 84687500, 2018, 'Christie\'s, New York', 'https://en.wikipedia.org/wiki/List_of_most_expensive_paintings'),
    ('vincent-van-gogh', 'Vincent van Gogh', '1853-1890', 'Hollanda', 'Post-Empresyonizm', 'public_domain', 'Laboureur dans un champ', '1889', 'https://upload.wikimedia.org/wikipedia/commons/c/c4/Laboureur_dans_un_champ_-_van_Gogh_%281889-1890%2C_Christie%27s%29.jpg', 81312500, 2017, 'Christie\'s, New York', 'https://en.wikipedia.org/wiki/List_of_most_expensive_paintings'),
    ('pablo-picasso', 'Pablo Picasso', '1881-1973', 'İspanya', 'Kübizm', 'dikkat', 'Femme aux Bras Croisés', '1902', 'https://upload.wikimedia.org/wikipedia/en/0/00/Pablo_Picasso%2C_1901-02%2C_Femme_aux_Bras_Crois%C3%A9s%2C_Woman_with_Folded_Arms_%28Madchenbildnis%29%2C_oil_on_canvas%2C_81_%C3%97_58_cm_%2832_%C3%97_23_in%29.jpg', 55006000, 2000, 'Christie\'s, New York', 'https://en.wikipedia.org/wiki/List_of_most_expensive_paintings'),
    ('wu-bin', 'Wu Bin', 'c. 1543 - c. 1626 (kesin tarihler bilinmiyor; 1573-1620 Wanli döneminde aktif)', 'Çin (Ming Hanedanlığı)', 'Ming Hanedanlığı edebiyatçı ressamları / Nanjing\'in "eksantrik" ressamları', 'public_domain', 'Ten Views of Lingbi Rock (十面靈璧圖卷, Bir Lingbi Taşının On Görünümü)', '1610', 'https://upload.wikimedia.org/wikipedia/commons/7/76/%E5%8D%81%E9%9D%A2%E7%81%B5%E7%92%A7%E5%9B%BE%E5%8D%B7.jpg', 77000000, 2020, 'Beijing Poly Auction (Poly Auction Beijing)', 'https://en.wikipedia.org/wiki/List_of_most_expensive_paintings'),
    ('pablo-picasso', 'Pablo Picasso', '1881-1973', 'İspanya', 'Kübizm', 'dikkat', 'Femme assise dans un jardin', '1938', 'https://cdn.gallerix.asia/sr/_EX/724395679/981707763.jpg', 49502500, 1999, 'Sotheby\'s, New York', 'https://en.wikipedia.org/wiki/List_of_most_expensive_paintings'),
    ('vincent-van-gogh', 'Vincent van Gogh', '1853-1890', 'Hollanda', 'Post-Empresyonizm', 'public_domain', 'Peasant Woman Against a Background of Wheat', '1890', 'https://upload.wikimedia.org/wikipedia/commons/f/ff/Vincent_Willem_van_Gogh_097.jpg', 47500000, 1997, 'Private sale via Acquavella Galleries Inc., New York', 'https://en.wikipedia.org/wiki/Peasant_Woman_Against_a_Background_of_Wheat'),
    ('andy-warhol', 'Andy Warhol', '1928-1987', 'ABD', 'Pop Art', 'dikkat', 'Four Marlons', '1966', 'https://upload.wikimedia.org/wikipedia/en/f/f5/Andy-Warhol-Four-Marlons.jpg', 69605000, 2014, 'Christie\'s, New York', 'https://en.wikipedia.org/wiki/Four_Marlons'),
    ('rene-magritte', 'René Magritte', '1898-1967', 'Belçika', 'Sürrealizm', 'dikkat', 'L\'Empire des lumières (The Empire of Light), 1961', '1961', 'https://cdn.sanity.io/images/cxgd3urn/production/551564416a95b3ea00e84f2d6aed8adf22981a1e-2000x1333.jpg?w=1200&h=720&q=85&fit=crop&auto=format', 79450000, 2022, 'Sotheby\'s, London', 'https://www.sothebys.com/en/press/one-of-the-most-desirable-works-of-modern-art-in-private-hands-rene-magrittes-lempire-des-lumieres-to-make-market-debut-at-sothebys-london'),
    ('andy-warhol', 'Andy Warhol', '1928-1987', 'ABD', 'Pop Art', 'dikkat', 'Men in Her Life', '1962', 'https://upload.wikimedia.org/wikipedia/en/5/55/Men_in_her_life_by_Andy_Warhol_%281962%29.jpg', 63362500, 2010, 'Phillips de Pury & Company', 'https://en.wikipedia.org/wiki/Men_in_Her_Life_(painting)'),
    ('fernand-leger', 'Fernand Léger', '1881-1955', 'Fransa', 'Kübizm', 'public_domain', 'Contraste de formes', '1913', 'https://upload.wikimedia.org/wikipedia/commons/9/9d/Contraste_de_formes%2C_1913_-_Fernand_L%C3%A9ger.jpg', 70062500, 2017, 'Christie\'s, New York', 'https://en.wikipedia.org/wiki/List_of_most_expensive_paintings'),
    ('vincent-van-gogh', 'Vincent van Gogh', '1853-1890', 'Hollanda', 'Post-Empresyonizm', 'public_domain', 'L\'Allée des Alyscamps', '1888', 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/32/Vincent_van_Gogh_-_L%27All%C3%A9e_des_Alyscamps.jpg/960px-Vincent_van_Gogh_-_L%27All%C3%A9e_des_Alyscamps.jpg', 66330000, 2015, 'Sotheby\'s, New York', 'https://en.wikipedia.org/wiki/List_of_most_expensive_paintings'),
    ('clyfford-still', 'Clyfford Still', '1904–1980', 'ABD', 'Soyut Dışavurumculuk (Renk Alanı Resmi)', 'dikkat', '1949-A-No. 1', '1949', 'https://resources.heni.com/02347e49-4caf-4dc1-aaf8-236f635734ce.jpg?width=1024', 61682500, 2011, 'Sotheby\'s, New York', 'https://en.wikipedia.org/wiki/List_of_most_expensive_paintings'),
    ('raphael', 'Raphael (Raffaello Sanzio)', '1483-1520', 'İtalya', 'Rönesans (Yüksek Rönesans)', 'public_domain', 'Sistine Madonna', '1513-1514', 'https://upload.wikimedia.org/wikipedia/commons/0/0c/Sistine_Madonna_%28original%29.jpg', 42500, 1759, 'Private sale', 'https://en.wikipedia.org/wiki/List_of_most_expensive_paintings'),
    ('jan-van-eyck', 'Jan van Eyck', 'yak. 1390-1441', 'Flandre (bugünkü Belçika)', 'Erken Flaman Resim Sanatı (Early Netherlandish)', 'public_domain', 'Gizemli Kuzu\'ya Tapınma (Gent Altarpiece)', '1432', 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Ghent_Altarpiece_-_Adoration_of_the_Mystic_Lamb.jpg/960px-Ghent_Altarpiece_-_Adoration_of_the_Mystic_Lamb.jpg', 80000, 1821, 'Private sale', 'https://en.wikipedia.org/wiki/List_of_most_expensive_paintings'),
    ('bartolome-esteban-murillo', 'Bartolomé Esteban Murillo', '1617-1682', 'İspanya', 'Barok (İspanyol Altın Çağı, Sevilla ekolü)', 'public_domain', 'The Immaculate Conception of Los Venerables', 'c. 1678', 'https://upload.wikimedia.org/wikipedia/commons/f/f4/Bartolom%C3%A9_Esteban_Perez_Murillo_005.jpg', 120000, 1852, 'Private sale (Jean-de-Dieu Soult koleksiyonundan satın alma, Louvre)', 'https://en.wikipedia.org/wiki/List_of_most_expensive_paintings'),
    ('raphael', 'Raphael (Raffaello Sanzio)', '1483-1520', 'İtalya', 'Rönesans (Yüksek Rönesans)', 'public_domain', 'Ansidei Madonna', '1505-1507', 'https://upload.wikimedia.org/wikipedia/commons/1/1c/PalaAnsidei.jpg', 350000, 1885, 'Private sale', 'https://en.wikipedia.org/wiki/List_of_most_expensive_paintings'),
    ('raphael', 'Raphael (Raffaello Sanzio)', '1483-1520', 'İtalya', 'Rönesans (Yüksek Rönesans)', 'public_domain', 'Colonna Altarpiece (Madonna and Child Enthroned with Saints)', 'c. 1503-1505', 'https://images.metmuseum.org/CRDImages/ep/original/DP-43051-001.jpg', 500000, 1901, 'Private sale', 'https://en.wikipedia.org/wiki/List_of_most_expensive_paintings'),
    ('anthony-van-dyck', 'Anthony van Dyck', '1599-1641', 'Flandre (Güney Hollanda, günümüz Belçika)', 'Barok', 'public_domain', 'Marchesa Elena Grimaldi Cattaneo', 'c. 1623', 'https://upload.wikimedia.org/wikipedia/commons/8/87/Marchesa_Elena_Grimaldi_c1623_Anthony_van_Dyck.jpg', 514400, 1906, 'Knoedler (özel satış)', 'https://en.wikipedia.org/wiki/List_of_most_expensive_paintings'),
    ('rembrandt', 'Rembrandt van Rijn', '1606-1669', 'Hollanda (Felemenk Cumhuriyeti)', 'Barok (Hollanda Altın Çağı)', 'public_domain', 'The Mill (Değirmen)', '1645/48', 'https://upload.wikimedia.org/wikipedia/commons/2/2f/DeMolenRembrandt.jpg', 514400, 1911, 'Private sale', 'https://en.wikipedia.org/wiki/The_Mill_(Rembrandt)'),
    ('raphael', 'Raphael (Raffaello Sanzio)', '1483-1520', 'İtalya', 'Rönesans (Yüksek Rönesans)', 'public_domain', 'Small Cowper Madonna', 'c. 1504-1505', 'https://upload.wikimedia.org/wikipedia/commons/6/6e/Raphael%2C_The_Small_Cowper_Madonna%2C_c._1505%2C_NGA_1196.jpg', 582500, 1913, 'Private sale', 'https://en.wikipedia.org/wiki/List_of_most_expensive_paintings'),
    ('leonardo-da-vinci', 'Leonardo da Vinci', '1452-1519', 'İtalya', 'Rönesans', 'public_domain', 'Benois Madonna', 'c. 1478–1480', 'https://upload.wikimedia.org/wikipedia/commons/c/c7/Madonna_benois_01.jpg', 1572000, 1914, 'Private sale', 'https://en.wikipedia.org/wiki/List_of_most_expensive_paintings'),
    ('johannes-vermeer', 'Johannes Vermeer', '1632-1675', 'Hollanda (Dutch Republic)', 'Hollanda Altın Çağı / Barok (Dutch Golden Age)', 'public_domain', 'Study of a Young Woman (Genç Bir Kadın Çalışması)', 'c. 1665-1667', 'https://images.metmuseum.org/CRDImages/ep/original/DP353256.jpg', 2000000, 1959, 'Private sale', 'https://en.wikipedia.org/wiki/List_of_most_expensive_paintings'),
    ('rembrandt', 'Rembrandt van Rijn', '1606-1669', 'Hollanda (Felemenk Cumhuriyeti)', 'Barok (Hollanda Altın Çağı)', 'public_domain', 'Aristotle with a Bust of Homer (Aristoteles, Homeros Büstü ile)', '1653', 'https://images.metmuseum.org/CRDImages/ep/original/DP-30758-001.jpg', 2300000, 1961, 'Parke-Bernet, New York', 'https://en.wikipedia.org/wiki/List_of_most_expensive_paintings'),
    ('leonardo-da-vinci', 'Leonardo da Vinci', '1452-1519', 'İtalya', 'Rönesans', 'public_domain', 'Ginevra de\' Benci', 'c. 1474-1478', 'https://upload.wikimedia.org/wikipedia/commons/3/39/Leonardo_da_Vinci_-_Ginevra_de%27_Benci_-_Google_Art_Project.jpg', 6000000, 1967, 'Private sale', 'https://en.wikipedia.org/wiki/List_of_most_expensive_paintings'),
    ('diego-velazquez', 'Diego Velázquez', '1599-1660', 'İspanya', 'Barok', 'public_domain', 'Portrait of Juan de Pareja', 'c. 1650', 'https://images.metmuseum.org/CRDImages/ep/original/DP-14286-001.jpg', 5500000, 1970, 'Christie\'s, London', 'https://en.wikipedia.org/wiki/List_of_most_expensive_paintings'),
    ('j-m-w-turner', 'J. M. W. Turner', '1775-1851', 'İngiltere', 'Romantizm', 'public_domain', 'Juliet and her Nurse', '1836', 'https://upload.wikimedia.org/wikipedia/commons/b/b1/J._M._W._Turner_-_Juliet_and_her_Nurse_%281836%29_Google_Art_Project.jpg', 6400000, 1980, 'Sotheby Parke Bernet, New York', 'https://en.wikipedia.org/wiki/List_of_most_expensive_paintings'),
    ('j-m-w-turner', 'J. M. W. Turner', '1775-1851', 'İngiltere', 'Romantizm', 'public_domain', 'Seascape: Folkestone', 'c. 1845', 'https://upload.wikimedia.org/wikipedia/commons/f/fe/J._M._W._Turner_-_Seascape%2C_Folkestone_%28c._1845%29.jpg', 10000000, 1984, 'Sotheby\'s Londra', 'https://en.wikipedia.org/wiki/List_of_most_expensive_paintings'),
    ('vincent-van-gogh', 'Vincent van Gogh', '1853-1890', 'Hollanda', 'Post-Empresyonizm', 'public_domain', 'Vase with Fifteen Sunflowers', '1889', 'https://commons.wikimedia.org/wiki/Special:FilePath/Van_Gogh_Vase_with_Fifteen_Sunflowers.jpg', 39700000, 1987, 'Christie\'s, London', 'https://en.wikipedia.org/wiki/List_of_most_expensive_paintings'),
    ('vincent-van-gogh', 'Vincent van Gogh', '1853-1890', 'Hollanda', 'Post-Empresyonizm', 'public_domain', 'Irises', '1889', 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Irises-Vincent_van_Gogh.jpg/960px-Irises-Vincent_van_Gogh.jpg', 53900000, 1987, 'Sotheby\'s, New York', 'https://en.wikipedia.org/wiki/List_of_most_expensive_paintings'),
    ('vincent-van-gogh', 'Vincent van Gogh', '1853-1890', 'Hollanda', 'Post-Empresyonizm', 'public_domain', 'Portrait of Joseph Roulin', '1889', 'https://upload.wikimedia.org/wikipedia/commons/0/03/WLA_moma_Vincent_van_Gogh_Portrait_of_Joseph_Roulin.jpg', 58000000, 1989, 'Private sale via Thomas Ammann, Fine Art Zurich', 'https://en.wikipedia.org/wiki/List_of_most_expensive_paintings'),
    ('gustav-klimt', 'Gustav Klimt', '1862-1918', 'Avusturya', 'Sembolizm', 'public_domain', 'Portrait of Adele Bloch-Bauer I', '1907', 'https://upload.wikimedia.org/wikipedia/commons/8/84/Gustav_Klimt_046.jpg', 135000000, 2006, 'Private sale via Christie\'s', 'https://en.wikipedia.org/wiki/Portrait_of_Adele_Bloch-Bauer_I'),
    ('jackson-pollock', 'Jackson Pollock', '1912-1956', 'ABD', 'Soyut Ekspresyonizm', 'dikkat', 'No. 5, 1948', '1948', 'https://upload.wikimedia.org/wikipedia/en/4/4a/No._5%2C_1948.jpg', 140000000, 2006, 'Sotheby\'s (özel satış)', 'https://en.wikipedia.org/wiki/No._5,_1948'),
    ('paul-cezanne', 'Paul Cézanne', '1839-1906', 'Fransa', 'Post-Empresyonizm', 'public_domain', 'The Card Players (Les Joueurs de cartes)', '1892-1893', 'https://upload.wikimedia.org/wikipedia/commons/9/93/Les_Joueurs_de_cartes%2C_par_Paul_C%C3%A9zanne%2C_collection_Al-Thani%2C_Yorck.jpg', 250000000, 2011, 'Private sale', 'https://en.wikipedia.org/wiki/List_of_most_expensive_paintings'),
    ('willem-de-kooning', 'Willem de Kooning', '1904-1997', 'Hollanda (ABD\'ye göç etti)', 'Soyut Dışavurumculuk (Abstract Expressionism)', 'dogrulanmis_serbest', 'Interchange', '1955', 'https://upload.wikimedia.org/wikipedia/en/5/5f/Photo_of_Interchanged_by_Willem_de_Kooning.jpg', 300000000, 2015, 'Private sale', 'https://en.wikipedia.org/wiki/List_of_most_expensive_paintings'),
    ('david-hockney', 'David Hockney', '1937 (hala hayatta)', 'Ingiltere', 'Pop Art / Ingiliz figuratif resim', 'dikkat', 'Portrait of an Artist (Pool with Two Figures)', '1972', 'https://live.staticflickr.com/4866/45869684622_db245b3200_b.jpg', 90300000, 2018, 'Christie\'s (New York)', 'https://en.wikipedia.org/wiki/List_of_most_expensive_artworks_by_living_artists'),
    ('jasper-johns', 'Jasper Johns', '1930-', 'ABD', 'Neo-Dada / Pop Art', 'dikkat', 'False Start', '1959', 'https://uploads0.wikiart.org/images/jasper-johns/false-start-1959.jpg!Large.jpg', 80000000, 2006, 'Private sale', 'https://en.wikipedia.org/wiki/List_of_most_expensive_artworks_by_living_artists'),
    ('ed-ruscha', 'Ed Ruscha', '1937-', 'ABD', 'Pop Art / Kavramsal Sanat', 'dikkat', 'Standard Station, Ten-Cent Western Being Torn in Half', '1964', 'https://resources.heni.com/b13f70d1-5ee0-41fe-9431-8472e7208426.jpg', 68300000, 2024, 'Christie\'s', 'https://en.wikipedia.org/wiki/List_of_most_expensive_artworks_by_living_artists'),
    ('sacha-jafri', 'Sacha Jafri', '1977 - ', 'Birleşik Krallık', 'Çağdaş sanat / soyut-figüratif (büyülü gerçekçilik etkili)', 'dikkat', 'The Journey of Humanity', '2020', 'https://media.assettype.com/gulfnews%2Fimport%2F2021%2F03%2F03%2FJafri_177f8d47f4f_large.jpg', 62000000, 2021, 'Humanity Inspired Royal Charity Auction, Dubai', 'https://en.wikipedia.org/wiki/List_of_most_expensive_artworks_by_living_artists'),
    ('gerhard-richter', 'Gerhard Richter', '1932-', 'Almanya', 'Fotogerçekçilik / Kapitalist Gerçekçilik / Soyut Sanat', 'dikkat', 'Domplatz, Mailand (Cathedral Square, Milan)', '1968', 'https://sothebys-com.brightspotcdn.com/dims4/default/25e6831/2147483647/strip/true/crop/2000x1897+0+0/resize/2880x2732!/format/webp/quality/90/?url=http%3A%2F%2Fsothebys-brightspot-migration.s3.amazonaws.com%2F23%2F31%2Fd9%2F616036ac8944b8642b5e816f937d0165f4b7b2e77084db26d22eb88365%2F428n08991-xxxxx.jpg', 37100000, 2013, 'Sotheby\'s', 'https://www.sothebys.com/en/auctions/ecatalogue/2013/may-2013-contemporary-evening-n08991/lot.20.html'),
    ('gerhard-richter', 'Gerhard Richter', '1932-', 'Almanya', 'Soyut Sanat / Kapitalist Gerçekçilik', 'dikkat', 'Abstraktes Bild (809-4)', '1994', 'https://greynotgrey.com/blog/wp-content/uploads/2012/10/Gerhard-Richter-Abstraktes-Bild.jpg', 34200000, 2012, 'Sotheby\'s', 'https://www.sothebys.com/en/auctions/ecatalogue/2012/contemporary-art-evening-auction-l12024/lot.15.html'),
    ('jasper-johns', 'Jasper Johns', '1930-', 'ABD', 'Neo-Dada / Pop Art', 'dikkat', 'White Flag', '1955', 'https://upload.wikimedia.org/wikipedia/commons/9/93/White_Flag_%28with_observer%29.jpg', 7000000, 1988, 'Christie\'s', 'https://en.wikipedia.org/wiki/List_of_most_expensive_artworks_by_living_artists'),
    ('jasper-johns', 'Jasper Johns', '1930-', 'ABD', 'Neo-Dada', 'dikkat', 'Diver', '1962-63', 'https://www.jasper-johns.org/assets/paintings/diver.jpg', 4180000, 1988, 'Christie\'s', 'https://en.wikipedia.org/wiki/List_of_most_expensive_artworks_by_living_artists'),
    ('salvador-dali', 'Salvador Dalí', '1904-1989', 'İspanya', 'Sürrealizm', 'dikkat', 'L\'Énigme du désir – Ma mère, ma mère, ma mère (The Enigma of Desire)', '1929', 'https://www.dalipaintings.com/assets/img/paintings/the-enigma-of-my-desire.jpg', 800000, 1982, 'Christie\'s', 'https://en.wikipedia.org/wiki/List_of_most_expensive_artworks_by_living_artists'),
    ('pablo-picasso', 'Pablo Picasso', '1881-1973', 'İspanya', 'Kübizm', 'dikkat', 'Death of Harlequin (La Mort d\'Arlequin)', '1905', 'https://uploads7.wikiart.org/images/pablo-picasso/harlequin-s-death-1906.jpg!Large.jpg', 220000, 1962, 'Sotheby\'s', 'https://en.wikipedia.org/wiki/List_of_most_expensive_artworks_by_living_artists'),
    ('pablo-picasso', 'Pablo Picasso', '1881-1973', 'İspanya', 'Kübizm', 'dikkat', 'La Belle Hollandaise', '1905', 'https://upload.wikimedia.org/wikipedia/en/7/7d/Pablo_Picasso%2C_1905%2C_La_Belle_Hollandaise%2C_gouache_on_cardboard_mounted_on_wood%2C_77.1_x_65.8_cm%2C_Queensland_Art_Gallery%2C_Sydney.jpg', 150000, 1959, 'Sotheby\'s', 'https://en.wikipedia.org/wiki/List_of_most_expensive_artworks_by_living_artists'),
    ('ernest-meissonier', 'Ernest Meissonier', '1815-1891', 'Fransa', 'Akademizm / Askeri-tarih türü resim', 'public_domain', '1807, Friedland', 'yak. 1861-1875', 'https://images.metmuseum.org/CRDImages/ep/original/DT2144.jpg', 66000, 1887, 'American Art Association (A.T. Stewart terekesi satışı)', 'https://en.wikipedia.org/wiki/List_of_most_expensive_artworks_by_living_artists'),
    ('jules-breton', 'Jules Breton', '1827-1906', 'Fransa', 'Realizm (natüralist köylü sahneleri)', 'public_domain', 'Les Communiantes (The Communicants)', '1884', 'https://upload.wikimedia.org/wikipedia/commons/1/1a/Jules_Breton_The_Communicants.jpg', 45000, 1886, 'Mary J. Morgan estate sale', 'https://en.wikipedia.org/wiki/List_of_most_expensive_artworks_by_living_artists'),
]
