# -*- coding: utf-8 -*-
# Muzayede Faz 11: "fiyatsiz" tablolar - gercek, taninmis, ama belgelenmis
# bir muzayede satisi OLMAYAN eserler (cogu muze koleksiyonunda, hic
# satilmamis). fiyat_usd=0 sentineli kullanilir: oyun bu tablolarda fiyat
# sorusunu hic sormaz, direkt "kimin eseri" turune gecer (bkz.
# muzayede/index.html, st.fiyatsiz). UYDURMA/TAHMINI FIYAT YOK - sadece
# soru atlaniyor.
#
# Faz 9/10'da 10 tabloya tamamlanamayan 12 ressam icin baslatildi, hedef
# tam karsilandi (34/34 aday bulundu, 2'si gorsel bulunamadigi icin
# cikarildi, 32 eklendi). Jackson Pollock ve Mark Rothko 9/10'da kaldi
# (telifli muze gorselleri Commons'ta/erisilebilir formatta yok).
#
# Alan sirasi ana DATA ile ayni ama fiyat_usd/satis_yili/muzayede_evi=0/0/''
# (fiyatsiz isareti): ressam_id, isim, dogum_olum, ulke, akim,
# risk_seviyesi, tablo_adi, tablo_yili, gorsel_url, fiyat_usd(=0),
# satis_yili(=0), muzayede_evi(=''), kaynak_url

FAZ11_DATA = [
    ('edward-hopper', 'Edward Hopper', '1882-1967', 'United States', 'Amerikan Realizmi', 'dikkat', 'Automat', '1927', 'https://upload.wikimedia.org/wikipedia/commons/b/bc/Automat-edward-hopper-1927.jpg', 0, 0, '', 'https://en.wikipedia.org/wiki/Automat_(Hopper)'),
    ('edward-hopper', 'Edward Hopper', '1882-1967', 'United States', 'Amerikan Realizmi', 'dikkat', 'Early Sunday Morning', '1930', 'https://upload.wikimedia.org/wikipedia/commons/a/ae/Early-sunday-morning-edward-hopper-1930.jpg', 0, 0, '', 'https://en.wikipedia.org/wiki/Early_Sunday_Morning'),
    ('egon-schiele', 'Egon Schiele', '1890-1918', 'Avusturya', 'Ekspresyonizm', 'public_domain', 'Die Familie (The Family)', '1918', 'https://upload.wikimedia.org/wikipedia/commons/d/dd/Egon_Schiele_-_Kauerndes_Menschenpaar_%28Die_Familie%29_-_4277_-_%C3%96sterreichische_Galerie_Belvedere.jpg', 0, 0, '', 'https://en.wikipedia.org/wiki/The_Family_(Schiele)'),
    ('egon-schiele', 'Egon Schiele', '1890-1918', 'Avusturya', 'Ekspresyonizm', 'public_domain', 'Der Tod und das Mädchen (Death and the Maiden)', '1915', 'https://upload.wikimedia.org/wikipedia/commons/0/01/Egon_Schiele_-_Tod_und_M%C3%A4dchen_-_3171_-_%C3%96sterreichische_Galerie_Belvedere.jpg', 0, 0, '', 'https://en.wikipedia.org/wiki/Death_and_the_Maiden_(Schiele)'),
    ('egon-schiele', 'Egon Schiele', '1890-1918', 'Avusturya', 'Ekspresyonizm', 'public_domain', 'Portrait of Wally Neuzil', '1912', 'https://upload.wikimedia.org/wikipedia/commons/6/66/Egon_Schiele_-_Portrait_of_Wally_Neuzil_-_Google_Art_Project.jpg', 0, 0, '', 'https://en.wikipedia.org/wiki/Portrait_of_Wally'),
    ('georgia-okeeffe', 'Georgia O\'Keeffe', '1887-1986', 'ABD', 'Amerikan Modernizmi', 'dikkat', 'Black Iris', '1926', 'https://upload.wikimedia.org/wikipedia/commons/6/6e/Georgia_O%27Keeffe_-_Black_Iris_1926_MET.jpg', 0, 0, '', 'https://www.metmuseum.org/art/collection/search/489813'),
    ('henri-matisse', 'Henri Matisse', '1869-1954', 'Fransa', 'Fovizm', 'dikkat', 'Woman with a Hat (Femme au chapeau)', '1905', 'https://upload.wikimedia.org/wikipedia/commons/6/64/Henri_Matisse%2C_Woman_with_a_Hat_%28Femme_au_chapeau%29%2C_SFMOMA_02.jpg', 0, 0, '', 'https://en.wikipedia.org/wiki/Woman_with_a_Hat'),
    ('henri-matisse', 'Henri Matisse', '1869-1954', 'Fransa', 'Fovizm', 'dikkat', 'The Green Stripe (Portrait of Madame Matisse)', '1905', 'https://upload.wikimedia.org/wikipedia/commons/d/dd/Henri_Matisse%2C_The_Green_Stripe_%28Portrait_of_Mme_Matisse%29%2C_1905._National_Gallery_Copenhagen.jpg', 0, 0, '', 'https://en.wikipedia.org/wiki/The_Green_Stripe'),
    ('henri-matisse', 'Henri Matisse', '1869-1954', 'Fransa', 'Fovizm', 'dikkat', 'Dance (La Danse II)', '1910', 'https://upload.wikimedia.org/wikipedia/commons/a/a7/Matissedance.jpg', 0, 0, '', 'https://en.wikipedia.org/wiki/Dance_(Matisse)'),
    ('henri-matisse', 'Henri Matisse', '1869-1954', 'Fransa', 'Fovizm', 'dikkat', 'The Dessert: Harmony in Red (The Red Room)', '1908', 'https://upload.wikimedia.org/wikipedia/commons/5/5d/Henri_Matisse_-_The_Red_Room-1908.jpg', 0, 0, '', 'https://commons.wikimedia.org/wiki/File:Henri_Matisse_-_The_Red_Room-1908.jpg'),
    ('paul-gauguin', 'Paul Gauguin', '1848-1903', 'Fransa', 'Post-Empresyonizm', 'public_domain', 'Femmes de Tahiti (Tahitian Women on the Beach)', '1891', 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Paul_Gauguin_056.jpg/500px-Paul_Gauguin_056.jpg', 0, 0, '', 'https://en.wikipedia.org/wiki/Tahitian_Women_on_the_Beach'),
    ('rene-magritte', 'René Magritte', '1898-1967', 'Belçika', 'Sürrealizm', 'dikkat', 'Le Faux Miroir (The False Mirror)', '1929', 'https://uploads0.wikiart.org/images/rene-magritte/the-false-mirror-1928(1).jpg!Large.jpg', 0, 0, '', 'https://www.moma.org/collection/works/78938'),
    ('rene-magritte', 'René Magritte', '1898-1967', 'Belçika', 'Sürrealizm', 'dikkat', 'La Durée poignardée (Time Transfixed)', '1938', 'https://uploads8.wikiart.org/images/rene-magritte/time-transfixed-1938(1).jpg!Large.jpg', 0, 0, '', 'https://www.artic.edu/artworks/34181/la-duree-poignardee-time-transfixed'),
    ('rene-magritte', 'René Magritte', '1898-1967', 'Belçika', 'Sürrealizm', 'dikkat', 'Les Amants (The Lovers)', '1928', 'https://upload.wikimedia.org/wikipedia/en/5/59/Ren%C3%A9_Magritte_-_The_Lovers_%28Les_Amants%29_1928.jpg', 0, 0, '', 'https://www.moma.org/collection/works/79933'),
    ('rene-magritte', 'René Magritte', '1898-1967', 'Belçika', 'Sürrealizm', 'dikkat', 'Golconde (Golconda)', '1953', 'https://d34wccushva2ab.cloudfront.net/iiif/3/tms-images/v_414_20200117_001c_v01_M/full/1024,/0/default.jpg', 0, 0, '', 'https://www.menil.org/collection/objects/4901-golconda-golconde'),
    ('agnes-martin', 'Agnes Martin', '1912-2004', 'Kanada doğumlu, ABD vatandaşı (Taos, New Mexico\'da yaşadı ve öldü)', 'Minimalizm', 'dikkat', 'Night Sea', '1963', 'https://d1hhug17qm51in.cloudfront.net/www-media/2026/06/08175951/FC.459_01_H02-web.jpg', 0, 0, '', 'https://www.sfmoma.org/artwork/FC.459/'),
    ('agnes-martin', 'Agnes Martin', '1912-2004', 'Kanada doğumlu, ABD vatandaşı (Taos, New Mexico\'da yaşadı ve öldü)', 'Minimalizm', 'dikkat', 'Wheat', '1957', 'https://d1hhug17qm51in.cloudfront.net/www-media/2026/05/12221051/FC.787_5064.10Z_MARTIN_NP14r4_FINAL-web.jpg', 0, 0, '', 'https://www.sfmoma.org/artwork/FC.787/'),
    ('agnes-martin', 'Agnes Martin', '1912-2004', 'Kanada doğumlu, ABD vatandaşı (Taos, New Mexico\'da yaşadı ve öldü)', 'Minimalizm', 'dikkat', 'White Flower', '1960', 'https://www.guggenheim.org/wp-content/uploads/1960/01/63.1653_ph_web-1.jpg', 0, 0, '', 'https://www.guggenheim.org/artwork/2803'),
    ('agnes-martin', 'Agnes Martin', '1912-2004', 'Kanada doğumlu, ABD vatandaşı (Taos, New Mexico\'da yaşadı ve öldü)', 'Minimalizm', 'dikkat', 'Morning', '1965', 'https://media.tate.org.uk/aztate-prd-ew-dg-wgtail-st1-ctr-data/images/.width-600_2RN0c7L.jpg', 0, 0, '', 'https://www.tate.org.uk/art/artworks/martin-morning-t01866'),
    ('andy-warhol', 'Andy Warhol', '1928-1987', 'ABD', 'Pop Art', 'dikkat', 'Marilyn Diptych', '1962', 'https://upload.wikimedia.org/wikipedia/en/8/87/Marilyndiptych.jpg', 0, 0, '', 'https://en.wikipedia.org/wiki/Marilyn_Diptych'),
    ('mark-rothko', 'Mark Rothko', '1903-1970', 'Letonya doğumlu, Amerika Birleşik Devletleri', 'Soyut Ekspresyonizm (Color Field)', 'dikkat', 'No. 14, 1960', '1960', 'https://d1hhug17qm51in.cloudfront.net/www-media/2026/07/14201629/97.524_01_H02.jpg', 0, 0, '', 'https://www.sfmoma.org/artwork/97.524/'),
    ('salvador-dali', 'Salvador Dalí', '1904-1989', 'İspanya', 'Sürrealizm', 'dikkat', 'Métamorphose de Narcisse (Metamorphosis of Narcissus)', '1937', 'https://upload.wikimedia.org/wikipedia/en/2/21/Metamorphosis_of_Narcissus.jpg', 0, 0, '', 'https://en.wikipedia.org/wiki/Metamorphosis_of_Narcissus'),
    ('salvador-dali', 'Salvador Dalí', '1904-1989', 'İspanya', 'Sürrealizm', 'dikkat', 'Cygnes reflétant des éléphants (Swans Reflecting Elephants)', '1937', 'https://upload.wikimedia.org/wikipedia/en/f/f6/Swans_reflecting_elephants.jpg', 0, 0, '', 'https://en.wikipedia.org/wiki/Swans_Reflecting_Elephants'),
    ('salvador-dali', 'Salvador Dalí', '1904-1989', 'İspanya', 'Sürrealizm', 'dikkat', 'Galatea of the Spheres', '1952', 'https://upload.wikimedia.org/wikipedia/en/0/08/Galaofspheres.JPG', 0, 0, '', 'https://en.wikipedia.org/wiki/Galatea_of_the_Spheres'),
    ('salvador-dali', 'Salvador Dalí', '1904-1989', 'İspanya', 'Sürrealizm', 'dikkat', 'The Elephants', '1948', 'https://upload.wikimedia.org/wikipedia/en/4/43/Dali_Elephants.jpg', 0, 0, '', 'https://en.wikipedia.org/wiki/The_Elephants'),
    ('yves-klein', 'Yves Klein', '1928-1962', 'Fransa', 'Nouveau Realisme (Monokrom Resim)', 'dikkat', 'Untitled Blue Monochrome (IKB 82)', '1959', 'https://www.guggenheim.org/wp-content/uploads/1959/01/2000.27_ph_web-1.jpg', 0, 0, '', 'https://www.guggenheim.org/artwork/5638'),
    ('yves-klein', 'Yves Klein', '1928-1962', 'Fransa', 'Nouveau Realisme (Monokrom Resim)', 'dikkat', 'Hiroshima (ANT 79)', '1961', 'https://d34wccushva2ab.cloudfront.net/iiif/3/tms-images/1982_59_DJ_20190429_014c_v01_M/full/1024,/0/default.jpg', 0, 0, '', 'https://www.menil.org/collection/objects/2679-hiroshima-ant-79'),
    ('yves-klein', 'Yves Klein', '1928-1962', 'Fransa', 'Nouveau Realisme (Monokrom Resim)', 'dikkat', 'Untitled Monogold (MG 7)', '1960', 'https://d34wccushva2ab.cloudfront.net/iiif/3/tms-images/1982_61_DJ_v01_M/full/806,/0/default.jpg', 0, 0, '', 'https://www.menil.org/collection/objects/2682-untitled-monogold-mg-7'),
    ('yves-klein', 'Yves Klein', '1928-1962', 'Fransa', 'Nouveau Realisme (Monokrom Resim)', 'dikkat', 'Blue Rain (Pluie Bleue) (S 36)', '1961', 'https://d34wccushva2ab.cloudfront.net/iiif/3/tms-images/1975_11_DJ_v03_M/full/1024,/0/default.jpg', 0, 0, '', 'https://www.menil.org/collection/objects/2683-blue-rain-pluie-bleue-s-36'),
    ('yves-klein', 'Yves Klein', '1928-1962', 'Fransa', 'Nouveau Realisme (Monokrom Resim)', 'dikkat', 'Untitled Blue Monochrome (IKB 42)', '1960', 'https://d34wccushva2ab.cloudfront.net/iiif/3/tms-images/1984_50_DJ_20250128_v02_M/full/1024,/0/default.jpg', 0, 0, '', 'https://www.menil.org/collection/objects/2331-untitled-blue-monochrome-ikb-42'),
    ('yves-klein', 'Yves Klein', '1928-1962', 'Fransa', 'Nouveau Realisme (Monokrom Resim)', 'dikkat', 'Bengal Fires -- One-Minute Blue Fire Painting (M 41)', '1957', 'https://d34wccushva2ab.cloudfront.net/iiif/3/tms-images/FO88_05_14MF_RR01/full/1024,/0/default.jpg', 0, 0, '', 'https://www.menil.org/collection/objects/2685-bengal-fires-one-minute-blue-fire-painting-m-41-feux-de-bengale-tableau-de-feu-bleu-d-une-minute-m41'),
    ('yves-klein', 'Yves Klein', '1928-1962', 'Fransa', 'Nouveau Realisme (Monokrom Resim)', 'dikkat', 'Blue Sponge (Éponge bleue)', '1959', 'https://www.guggenheim.org/wp-content/uploads/1959/01/64.1752_ph_web-1.jpg', 0, 0, '', 'https://www.guggenheim.org/artwork/2197'),
]
