/* günün kelimesi — vitrin için seçme kelimeler (kelimece cevaplarından ayrı liste, oyunu bozmaz) */
const GUNLUK = [
  {k:"yakamoz", a:"geceleyin denizde kıpırtıyla beliren ışıltı"},
  {k:"seher", a:"tan yeri ağarmadan önceki vakit"},
  {k:"fecir", a:"tan ağartısı, gün doğumu kızıllığı"},
  {k:"gurup", a:"gün batımı"},
  {k:"mehtap", a:"ay ışığı"},
  {k:"ayla", a:"ayın çevresinde görülen ışık halkası"},
  {k:"şebnem", a:"gecenin yapraklarda bıraktığı nem, çiy"},
  {k:"jale", a:"çiy tanesi"},
  {k:"katre", a:"damla"},
  {k:"şule", a:"alev, ışık parıltısı"},
  {k:"ziya", a:"ışık"},
  {k:"şavk", a:"ışık, parıltı"},
  {k:"hare", a:"kimi yüzeylerde görülen dalgalı parıltı"},
  {k:"meneviş", a:"yüzeyde dalgalanan renk ve ışık oyunu"},
  {k:"serap", a:"sıcakta uzaktan su gibi görünen yanıltıcı görüntü"},
  {k:"ılgım", a:"sıcak havada titreyen görüntü, serap"},
  {k:"hülya", a:"tatlı hayal, kuruntu"},
  {k:"efsun", a:"büyü, sihir"},
  {k:"nihan", a:"gizli, saklı"},
  {k:"müphem", a:"belli belirsiz, kapalı"},
  {k:"deruni", a:"içten, içe değgin"},
  {k:"hercai", a:"kararsız, her telden çalan; bir menekşe"},
  {k:"melal", a:"usanç, iç sıkıntısı"},
  {k:"vuslat", a:"sevilene kavuşma"},
  {k:"hicran", a:"ayrılık ve onun yürekte bıraktığı acı"},
  {k:"firkat", a:"ayrılık"},
  {k:"sıla", a:"doğup büyünen yer; ona kavuşma"},
  {k:"yâd", a:"anma, hatırlama"},
  {k:"yâren", a:"yakın, sevilen dost"},
  {k:"hemhal", a:"aynı durumda olan, dert ortağı"},
  {k:"hasbihal", a:"baş başa dertleşme, söyleşi"},
  {k:"âsude", a:"sessiz, sakin, rahat"},
  {k:"müsterih", a:"içi rahat, kaygısız"},
  {k:"inşirah", a:"iç açılması, ferahlık"},
  {k:"sürur", a:"sevinç"},
  {k:"neşve", a:"sevinç, keyif"},
  {k:"bahtiyar", a:"mutlu, talihli"},
  {k:"nazenin", a:"ince, narin, cilveli"},
  {k:"nadide", a:"az bulunur, değerli"},
  {k:"yekta", a:"eşsiz, biricik"},
  {k:"müstesna", a:"benzerlerinden ayrı, seçkin"},
  {k:"yegâne", a:"biricik, tek"},
  {k:"avare", a:"işsiz güçsüz gezen, başıboş"},
  {k:"biçare", a:"çaresiz, zavallı"},
  {k:"derbeder", a:"dağınık, düzensiz yaşayan"},
  {k:"serzeniş", a:"sitem, çıkışma"},
  {k:"letafet", a:"hoşluk, incelik"},
  {k:"dilbaz", a:"tatlı dilli, söz ustası"},
  {k:"gamze", a:"gülerken yanakta beliren çukur"},
  {k:"imge", a:"zihinde canlandırılan görüntü; şiirin yapıtaşı"},
  {k:"imgelem", a:"hayal gücü"},
  {k:"düşlem", a:"hayal, fantezi"},
  {k:"yazın", a:"edebiyat"},
  {k:"güzelduyu", a:"estetik"},
  {k:"telmih", a:"söz arasında bilinen bir olaya dokundurma"},
  {k:"istiare", a:"eğretileme; sözü benzetme yoluyla başka anlamda kullanma"},
  {k:"mazmun", a:"divan şiirinde kalıplaşmış ince imge"},
  {k:"nazire", a:"bir şiire aynı ölçü ve uyakla yazılan karşılık"},
  {k:"redif", a:"uyaktan sonra yinelenen ek ya da söz"},
  {k:"tını", a:"bir sesi öbürlerinden ayıran renk"},
  {k:"nağme", a:"ezgi, güzel ses"},
  {k:"ahenk", a:"uyum, düzen"},
  {k:"kandil", a:"yağ ve fitille yanan eski aydınlatma aracı"},
  {k:"fanus", a:"ışığı rüzgârdan koruyan cam kap"},
  {k:"heybe", a:"omuza asılan iki gözlü torba"},
  {k:"ibrişim", a:"bükülmüş ipek iplik"},
  {k:"atlas", a:"yüzü parlak, sık dokunmuş ipek kumaş"},
  {k:"kehribar", a:"süs taşı olan fosil reçine; koyu sarı"},
  {k:"firuze", a:"gök mavisi değerli taş"},
  {k:"sedef", a:"deniz kabuğunun içindeki parlak katman"},
  {k:"eflatun", a:"açık mor"},
  {k:"zerrin", a:"nergis türünden sarı çiçek; altın sarısı"},
  {k:"gonca", a:"açılmamış çiçek, tomurcuk gül"},
  {k:"şakayık", a:"iri, katmerli çiçekli süs bitkisi"},
  {k:"ıtır", a:"güzel koku; kokulu bir saksı bitkisi"},
  {k:"reyhan", a:"fesleğen"},
  {k:"hanımeli", a:"güzel kokulu, sarmaşık bir süs bitkisi"},
  {k:"müge", a:"inci çiçeği"},
  {k:"kardelen", a:"kar altında açan ilk bahar çiçeği"},
  {k:"çiğdem", a:"baharda açan soğanlı kır çiçeği"},
  {k:"günebakan", a:"ayçiçeği"},
  {k:"meltem", a:"yazın düzenli esen hafif rüzgâr"},
  {k:"imbat", a:"yazın denizden karaya esen serinletici meltem"},
  {k:"poyraz", a:"kuzeydoğudan esen soğuk rüzgâr"},
  {k:"lodos", a:"güneybatıdan esen ılık rüzgâr"},
  {k:"karayel", a:"kuzeybatıdan esen sert rüzgâr"},
  {k:"keşişleme", a:"güneydoğudan esen rüzgâr"},
  {k:"ayaz", a:"duru gecelerin kuru soğuğu"},
  {k:"çisenti", a:"ince ince yağan yağmur"},
  {k:"pus", a:"hafif sis, duman"},
  {k:"duru", a:"bulanıklığı olmayan, temiz"},
  {k:"umman", a:"büyük deniz, okyanus"},
  {k:"derya", a:"deniz"},
  {k:"mavera", a:"öte; görünenin ardındaki dünya"},
  {k:"menzil", a:"varılacak yer; yolculukta konak"},
  {k:"patika", a:"keçi yolu, ince dağ yolu"},
  {k:"koyak", a:"iki dağ arasındaki çukur yer, vadi"},
  {k:"yalıyar", a:"kıyıda dimdik yükselen kayalık, falez"},
  {k:"düden", a:"suların yer altına daldığı doğal kuyu"},
  {k:"obruk", a:"çökmeyle oluşan derin doğal çukur"}
];

function gununKelimesi(){
  const baslangic = new Date(2026, 0, 1);
  const gun = Math.floor((Date.now() - baslangic) / 86400000);
  return GUNLUK[((gun * 131 + 7) % GUNLUK.length + GUNLUK.length) % GUNLUK.length];
}
