/* makas — veri: film havuzu (otomatik tamamlama) + günlük harman bulmacaları
   film: [türkçe ad, orijinal ad, yıl] — türkçe ad = vizyon adı; aynıysa orijinal boş "" */
window.MAKAS_VERI = {

milat: [2026, 6, 2],   // 2 Temmuz 2026 = Makas #1 (ay 0 tabanlı)

filmler: [
["Esaretin Bedeli","The Shawshank Redemption",1994],
["Baba","The Godfather",1972],
["Baba 2","The Godfather Part II",1974],
["Kara Şövalye","The Dark Knight",2008],
["Schindler'in Listesi","Schindler's List",1993],
["Yüzüklerin Efendisi: Yüzük Kardeşliği","The Lord of the Rings: The Fellowship of the Ring",2001],
["Yüzüklerin Efendisi: İki Kule","The Lord of the Rings: The Two Towers",2002],
["Yüzüklerin Efendisi: Kralın Dönüşü","The Lord of the Rings: The Return of the King",2003],
["Ucuz Roman","Pulp Fiction",1994],
["Dövüş Kulübü","Fight Club",1999],
["Forrest Gump","",1994],
["Başlangıç","Inception",2010],
["Matrix","The Matrix",1999],
["Sıkı Dostlar","Goodfellas",1990],
["Yedi","Se7en",1995],
["Kuzuların Sessizliği","The Silence of the Lambs",1991],
["Yıldızlararası","Interstellar",2014],
["Er Ryan'ı Kurtarmak","Saving Private Ryan",1998],
["Yeşil Yol","The Green Mile",1999],
["Sevginin Gücü","Léon: The Professional",1994],
["Geleceğe Dönüş","Back to the Future",1985],
["Prestij","The Prestige",2006],
["Gladyatör","Gladiator",2000],
["Titanic","",1997],
["Köstebek","The Departed",2006],
["Whiplash","",2014],
["Yaratık","Alien",1979],
["Kıyamet","Apocalypse Now",1979],
["Akıl Defteri","Memento",2000],
["Kutsal Hazine Avcıları","Raiders of the Lost Ark",1981],
["Aslan Kral","The Lion King",1994],
["Piyanist","The Pianist",2002],
["Terminatör","The Terminator",1984],
["Terminatör 2: Mahşer Günü","Terminator 2: Judgment Day",1991],
["Cennet Sineması","Cinema Paradiso",1988],
["Sapık","Psycho",1960],
["Casablanca","",1942],
["Modern Zamanlar","Modern Times",1936],
["Şehir Işıkları","City Lights",1931],
["Arka Pencere","Rear Window",1954],
["Ölüm Korkusu","Vertigo",1958],
["Yurttaş Kane","Citizen Kane",1941],
["12 Öfkeli Adam","12 Angry Men",1957],
["2001: Uzay Yolu Macerası","2001: A Space Odyssey",1968],
["Otomatik Portakal","A Clockwork Orange",1971],
["Cinnet","The Shining",1980],
["Full Metal Jacket","",1987],
["Guguk Kuşu","One Flew Over the Cuckoo's Nest",1975],
["Taksi Şoförü","Taxi Driver",1976],
["Truman Show","The Truman Show",1998],
["Yeni Hayat","Cast Away",2000],
["Sıkıysa Yakala","Catch Me If You Can",2002],
["Terminal","The Terminal",2004],
["Yerçekimi","Gravity",2013],
["Marslı","The Martian",2015],
["VOL-İ","WALL-E",2008],
["Yukarı Bak","Up",2009],
["Coco","",2017],
["Ters Yüz","Inside Out",2015],
["Oyuncak Hikayesi","Toy Story",1995],
["Kayıp Balık Nemo","Finding Nemo",2003],
["Ratatuy","Ratatouille",2007],
["Sevimli Canavarlar","Monsters, Inc.",2001],
["Şrek","Shrek",2001],
["Ruhların Kaçışı","Spirited Away",2001],
["Komşum Totoro","My Neighbor Totoro",1988],
["Yürüyen Şato","Howl's Moving Castle",2004],
["Ateşböceklerinin Mezarı","Grave of the Fireflies",1988],
["Parazit","Parasite",2019],
["İhtiyar Delikanlı","Oldboy",2003],
["Amélie","Le Fabuleux Destin d'Amélie Poulain",2001],
["Can Dostum","The Intouchables",2011],
["Can Dostum","Good Will Hunting",1997],
["Hayat Güzeldir","La vita è bella",1997],
["La La Land","",2016],
["Büyük Budapeşte Oteli","The Grand Budapest Hotel",2014],
["Birdman","",2014],
["Diriliş","The Revenant",2015],
["Joker","",2019],
["Avengers: Endgame","",2019],
["Avatar","",2009],
["Jurassic Park","",1993],
["Denizin Dişleri","Jaws",1975],
["King Kong","",2005],
["E.T.","E.T. the Extra-Terrestrial",1982],
["Yıldız Savaşları","Star Wars",1977],
["İmparator'un Dönüşü","The Empire Strikes Back",1980],
["Harry Potter ve Felsefe Taşı","Harry Potter and the Philosopher's Stone",2001],
["Hobbit: Beklenmedik Yolculuk","The Hobbit: An Unexpected Journey",2012],
["Karayip Korsanları: Siyah İnci'nin Laneti","Pirates of the Caribbean: The Curse of the Black Pearl",2003],
["Altıncı His","The Sixth Sense",1999],
["Diğerleri","The Others",2001],
["Zindan Adası","Shutter Island",2010],
["Akıl Oyunları","A Beautiful Mind",2001],
["Kelebek Etkisi","The Butterfly Effect",2004],
["Bugün Aslında Dündü","Groundhog Day",1993],
["Sil Baştan","Eternal Sunshine of the Spotless Mind",2004],
["Bir Rüya İçin Ağıt","Requiem for a Dream",2000],
["Siyah Kuğu","Black Swan",2010],
["Trainspotting","",1996],
["Büyük Lebowski","The Big Lebowski",1998],
["İhtiyarlara Yer Yok","No Country for Old Men",2007],
["Fargo","",1996],
["Kan Dökülecek","There Will Be Blood",2007],
["Zincirsiz","Django Unchained",2012],
["Soysuzlar Çetesi","Inglourious Basterds",2009],
["Kill Bill","Kill Bill: Vol. 1",2003],
["Rezervuar Köpekleri","Reservoir Dogs",1992],
["Bir Zamanlar Hollywood'da","Once Upon a Time in Hollywood",2019],
["Bir Zamanlar Batıda","Once Upon a Time in the West",1968],
["İyi, Kötü ve Çirkin","The Good, the Bad and the Ugly",1966],
["Amadeus","",1984],
["Cesur Yürek","Braveheart",1995],
["Rocky","",1976],
["Milyonluk Bebek","Million Dollar Baby",2004],
["Gran Torino","",2008],
["Umudunu Kaybetme","The Pursuit of Happyness",2006],
["Ölü Ozanlar Derneği","Dead Poets Society",1989],
["Bıçaklar Çekildi","Knives Out",2019],
["Bıçak Sırtı","Blade Runner",1982],
["Geliş","Arrival",2016],
["Dune: Çöl Gezegeni","Dune",2021],
["Mad Max: Öfkeli Yollar","Mad Max: Fury Road",2015],
["Aşk","Her",2013],
["Sürücü","Drive",2011],
["Sosyal Ağ","The Social Network",2010],
["Milyoner","Slumdog Millionaire",2008],
["Kayıp Kız","Gone Girl",2014],
["Zodiac","",2007],
["Tutsak","Prisoners",2013],
["Gece Vurgunu","Nightcrawler",2014],
["Amerikan Güzeli","American Beauty",1999],
["Geçmişin Gölgesinde","American History X",1998],
["Olağan Şüpheliler","The Usual Suspects",1995],
["Los Angeles Sırları","L.A. Confidential",1997],
["Büyük Hesaplaşma","Heat",1995],
["Yaralı Yüz","Scarface",1983],
["Para Avcısı","The Wolf of Wall Street",2013],
["12 Yıllık Esaret","12 Years a Slave",2013],
["Zoraki Kral","The King's Speech",2010],
["Enigma","The Imitation Game",2014],
["Bohemian Rhapsody","",2018],
["Yeşil Rehber","Green Book",2018],
["Not Defteri","The Notebook",2004],
["Aşk ve Gurur","Pride & Prejudice",2005],
["Muhteşem Gatsby","The Great Gatsby",2013],
["Büyük Balık","Big Fish",2003],
["Makas Eller","Edward Scissorhands",1990],
["Charlie'nin Çikolata Fabrikası","Charlie and the Chocolate Factory",2005],
["Evde Tek Başına","Home Alone",1990],
["Maske","The Mask",1994],
["Müthiş Dadı","Mrs. Doubtfire",1993],
["Jumanji","",1995],
["Zor Ölüm","Die Hard",1988],
["Hız Tuzağı","Speed",1994],
["Kaçak","The Fugitive",1993],
["Görevimiz Tehlike","Mission: Impossible",1996],
["Skyfall","",2012],
["Geçmişi Olmayan Adam","The Bourne Identity",2002],
["John Wick","",2014],
["Yedi Samuray","Seven Samurai",1954],
["Rashomon","",1950],
["Bisiklet Hırsızları","Bicycle Thieves",1948],
["Sekiz Buçuk","8½",1963],
["Tatlı Hayat","La Dolce Vita",1960],
["400 Darbe","The 400 Blows",1959],
["Postacı","Il Postino",1994],
["Merkez İstasyonu","Central do Brasil",1998],
["Tanrı Kent","City of God",2002],
["Pan'ın Labirenti","Pan's Labyrinth",2006],
["Başkalarının Hayatı","The Lives of Others",2006],
["Çöküş","Downfall",2004],
["Das Boot","",1981],
["Bir Ayrılık","A Separation",2011],
["Hababam Sınıfı","",1975],
["Tosun Paşa","",1976],
["Süt Kardeşler","",1976],
["Kibar Feyzo","",1978],
["Çöpçüler Kralı","",1977],
["Davaro","",1981],
["Züğürt Ağa","",1985],
["Neşeli Günler","",1978],
["Banker Bilo","",1980],
["Selvi Boylum Al Yazmalım","",1977],
["Muhsin Bey","",1987],
["Eşkıya","",1996],
["Yol","",1982],
["Susuz Yaz","",1963],
["Sürü","",1978],
["Umut","",1970],
["Gelin","",1973],
["Vesikalı Yarim","",1968],
["Ah Güzel İstanbul","",1966],
["Sevmek Zamanı","",1965],
["Kış Uykusu","",2014],
["Bir Zamanlar Anadolu'da","",2011],
["Üç Maymun","",2008],
["Uzak","",2002],
["Babam ve Oğlum","",2005],
["Vizontele","",2001],
["G.O.R.A.","",2004],
["A.R.O.G","",2008],
["Organize İşler","",2005],
["Recep İvedik","",2008],
["Dondurmam Gaymak","",2006],
["Ayla","Ayla: The Daughter of War",2017],
["Müslüm","",2018],
["7. Koğuştaki Mucize","",2019],
["Masumiyet","",1997],
["Gemide","",1998],
["Propaganda","",1999],
["Kabadayı","",2007]
],

/* her bulmaca: iki filmin tek hikâye gibi harmanlanmış özeti.
   es: kabul edilen adlar (öneki eşleşen film de sayılır — alt başlıklar böyle yakalanır) */
bulmacalar: [
{
 a:{ad:"Titanic", es:["titanic"], yil:1997, tur:"romantik dram", yon:"James Cameron", oy:"Kate Winslet"},
 b:{ad:"Yüzüklerin Efendisi", es:["yüzüklerin efendisi","the lord of the rings","lotr"], yil:2001, tur:"fantastik macera", yon:"Peter Jackson", oy:"Elijah Wood"},
 m:"Yaşlı bir kadın, gençliğinde batan bir gemide yaşadığı aşkı ve herkesin gözünü diktiği o paha biçilmez takıyı anlatır. Takıyı sonunda okyanusun karanlığına bırakmıştır; oysa bilenler bilir — o şeyden gerçekten kurtulmanın tek yolu, onu ta bir yanardağın ağzına kadar yürüyerek götürmektir."
},
{
 a:{ad:"Matrix", es:["matrix","the matrix"], yil:1999, tur:"bilimkurgu", yon:"Wachowski kardeşler", oy:"Keanu Reeves"},
 b:{ad:"Başlangıç", es:["başlangıç","inception"], yil:2010, tur:"bilimkurgu", yon:"Christopher Nolan", oy:"Leonardo DiCaprio"},
 m:"Bilgisayar başında sıradan bir hayat süren adam, gerçek sandığı dünyanın aslında zihnine kurulmuş bir düş olduğunu öğrenir. Üstelik yeni işi de tam bunun üzerine: bir ekiple başkalarının rüyalarına dalıp en dibe, rüyanın içindeki rüyaya bir fikir yerleştirecektir. Kırmızı hapı çoktan yuttu; şimdi tek derdi, topacın dönmeye devam edip etmediği."
},
{
 a:{ad:"Truman Show", es:["truman show","the truman show"], yil:1998, tur:"dram-komedi", yon:"Peter Weir", oy:"Jim Carrey"},
 b:{ad:"Yeni Hayat", es:["yeni hayat","cast away"], yil:2000, tur:"macera-dram", yon:"Robert Zemeckis", oy:"Tom Hanks"},
 m:"Uçağı okyanusa düşen adam, ıssız bir adada yıllarca tek başına yaşar; en yakın dostu, üzerine yüz çizdiği bir voleybol topudur. Sonunda kendine bir sal yapıp denize açılır — ta ki salın burnu gökyüzüne boyanmış dev bir duvara toslayana ve yukarılardan bir yerden 'kestik!' sesi gelene kadar."
},
{
 a:{ad:"Hababam Sınıfı", es:["hababam sınıfı"], yil:1975, tur:"komedi", yon:"Ertem Eğilmez", oy:"Kemal Sunal"},
 b:{ad:"Ölü Ozanlar Derneği", es:["ölü ozanlar derneği","dead poets society"], yil:1989, tur:"dram", yon:"Peter Weir", oy:"Robin Williams"},
 m:"Yatılı okulun arka sıraları, kopya düzeneğinden sahte veli imzasına kadar her yolu denemiş, müdür muavinini deliye çevirmiş bir sınıftır. Derken okula genç bir edebiyat öğretmeni gelir; onları sıraların üstüne çıkarır ve 'anı yakala' der. Sınıfın en çalışkan(!) üyesinin buna ne dediği kayıtlara geçmemiştir."
},
{
 a:{ad:"Eşkıya", es:["eşkıya"], yil:1996, tur:"dram", yon:"Yavuz Turgul", oy:"Şener Şen"},
 b:{ad:"Baba", es:["baba","the godfather"], yil:1972, tur:"suç filmi", yon:"Francis Ford Coppola", oy:"Marlon Brando"},
 m:"Otuz beş yıl yattığı dağ hapishanesinden çıkıp İstanbul'a inen son eşkıya, şehirde bambaşka bir düzen bulur: aile artık zeytinyağı işinde değildir, kimse kimseye hayır diyememektedir ve reddedilemeyecek teklifler havada uçuşmaktadır. Küçük oğul aile işlerinden uzak durmaya yeminlidir — babası köşe başında vurulana kadar."
},
{
 a:{ad:"Geleceğe Dönüş", es:["geleceğe dönüş","back to the future"], yil:1985, tur:"bilimkurgu-komedi", yon:"Robert Zemeckis", oy:"Michael J. Fox"},
 b:{ad:"Yıldızlararası", es:["yıldızlararası","interstellar"], yil:2014, tur:"bilimkurgu", yon:"Christopher Nolan", oy:"Matthew McConaughey"},
 m:"Bir garajdan fırlayan araç zamanda yolculuğa çıkar; sürücü önce kendi annesinin ona âşık olmasını engellemek zorunda kalır, sonra bir kara deliğin kıyısında birkaç saat oyalanıp döndüğünde kızının kendisinden yaşlı olduğunu görür. Kitaplığın arkasından ona işaretlerle seslenen de zaten kendisidir."
},
{
 a:{ad:"Amélie", es:["amelie","amélie"], yil:2001, tur:"romantik komedi", yon:"Jean-Pierre Jeunet", oy:"Audrey Tautou"},
 b:{ad:"Yedi", es:["yedi","se7en","seven"], yil:1995, tur:"polisiye gerilim", yon:"David Fincher", oy:"Brad Pitt"},
 m:"Paris'te bir kafede çalışan utangaç genç kadın, tanımadığı insanların hayatına gizlice küçük iyilikler bırakmaktadır: bir hazine kutusu, bir mektup, seyahate çıkmış bir bahçe cücesi. Şehrin öbür yakasında ise biri tam tersini yapmakta, yedi ölümcül günahı tek tek işleyip ardında izler bırakmaktadır. Son teslimat bir koli — içinde ne olduğunu, emekliliğine bir hafta kalmış dedektif bile tahmin edemez."
},
{
 a:{ad:"Parazit", es:["parazit","parasite"], yil:2019, tur:"kara komedi", yon:"Bong Joon-ho", oy:"Song Kang-ho"},
 b:{ad:"Bıçaklar Çekildi", es:["bıçaklar çekildi","knives out"], yil:2019, tur:"polisiye", yon:"Rian Johnson", oy:"Daniel Craig"},
 m:"Yoksul bir aile, sahte diplomalar ve ince tezgâhlarla zengin bir konağa tek tek sızar: özel öğretmen, şoför, hizmetçi... Derken evin yaşlı ve zengin sahibi bir sabah boğazı kesilmiş bulunur ve konağa, aksanı tuhaf, meşhur bir özel dedektif gelir. Bodrum kattaki kapıyı henüz kimse açmamıştır."
},
{
 a:{ad:"Aslan Kral", es:["aslan kral","the lion king","lion king"], yil:1994, tur:"animasyon", yon:"Disney (Allers & Minkoff)", oy:"—"},
 b:{ad:"Coco", es:["coco"], yil:2017, tur:"animasyon", yon:"Pixar (Lee Unkrich)", oy:"—"},
 m:"Babasını genç yaşta kaybeden veliaht, ölümden kendini sorumlu tutup diyar diyar kaçar; 'gam yok, tasa yok' diye yaşamayı öğrenir. Ta ki bir gece kendini ölüler diyarında bulup, ailenin nesillerdir süren müzik yasağının ardındaki gerçeği öğrenene kadar. Meğer her şeyin başında yine bir amca varmış."
},
{
 a:{ad:"VOL-İ", es:["vol-i","voli","wall-e","walle"], yil:2008, tur:"animasyon", yon:"Pixar (Andrew Stanton)", oy:"—"},
 b:{ad:"Yerçekimi", es:["yerçekimi","gravity"], yil:2013, tur:"bilimkurgu gerilim", yon:"Alfonso Cuarón", oy:"Sandra Bullock"},
 m:"Dünyanın yüzlerce kilometre yukarısında her şey bir enkaza dönüşür; sağ kalan tek kişi, nefesi azalırken istasyondan istasyona savrulur. Aşağıda, çoktan terk edilmiş gezegende ise küçük bir robot sabırla çöp istiflemekte ve bir gün gökten inecek zarif, beyaz ziyaretçiye uzatacağı filizi saklamaktadır."
},
{
 a:{ad:"Cinnet", es:["cinnet","the shining","shining"], yil:1980, tur:"korku", yon:"Stanley Kubrick", oy:"Jack Nicholson"},
 b:{ad:"Büyük Budapeşte Oteli", es:["büyük budapeşte oteli","the grand budapest hotel","grand budapest"], yil:2014, tur:"komedi", yon:"Wes Anderson", oy:"Ralph Fiennes"},
 m:"Dağların arasındaki görkemli otel, yaz misafirlerini efsanevi başkomiserinin kusursuz nezaketiyle ağırlar; adam bir de yaşlı ve zengin hanım müşterilerin gönlünü almasıyla meşhurdur. Kış gelip otel boşalınca anahtarlar, romanını yazmaya gelen bekçiye ve ailesine teslim edilir. Kendisine yalnızca tek bir oda tembihlenmiştir: 237'ye girme."
},
{
 a:{ad:"G.O.R.A.", es:["gora","g.o.r.a."], yil:2004, tur:"bilimkurgu-komedi", yon:"Ömer Faruk Sorak", oy:"Cem Yılmaz"},
 b:{ad:"Yıldız Savaşları", es:["yıldız savaşları","star wars","yeni bir umut","a new hope"], yil:1977, tur:"uzay operası", yon:"George Lucas", oy:"Mark Hamill"},
 m:"Halı pazarlayan kurnaz bir adam, bir gece uzaylılarca kaçırılıp uzak bir gezegene götürülür. Orada çölde büyümüş genç bir çiftçiyle tanışır: çocuğun babası, meğer o maskeli, siyah pelerinli, hırıltılı nefesli adamın ta kendisidir. İkisi birlikte hem prensesi kurtaracak hem de gezegenleri buharlaştıran küresel silahı, tek zayıf noktasından vuracaktır."
},
{
 a:{ad:"Vizontele", es:["vizontele"], yil:2001, tur:"dram-komedi", yon:"Yılmaz Erdoğan", oy:"Yılmaz Erdoğan"},
 b:{ad:"Cennet Sineması", es:["cennet sineması","cinema paradiso"], yil:1988, tur:"dram", yon:"Giuseppe Tornatore", oy:"Philippe Noiret"},
 m:"Ücra bir kasabaya bir gün anteniyle, lambalarıyla tuhaf bir kutu gelir: kimine göre şeytan icadı, kimine göre geleceğin ta kendisi. Kasabanın küçük oğlanı ise büyüyü çoktan keşfetmiştir; makinist amcanın dizinin dibinde, perdedeki öpüşme sahnelerinden kesilip atılan film parçalarını biriktirmektedir. Yıllar sonra büyük şehirden döndüğünde onu, bu kesiklerden yapılmış bir makara beklemektedir."
},
{
 a:{ad:"Babam ve Oğlum", es:["babam ve oğlum"], yil:2005, tur:"dram", yon:"Çağan Irmak", oy:"Çetin Tekindor"},
 b:{ad:"Büyük Balık", es:["büyük balık","big fish"], yil:2003, tur:"fantastik dram", yon:"Tim Burton", oy:"Ewan McGregor"},
 m:"Ölmek üzere olan babanın anlattığı hayat hikâyesi devlere, cadılara, dev balıklara varır; oğul hangi kısmın gerçek olduğunu hiç bilemez. Asıl anlatılamayan hikâye ise bir darbe sabahına denk gelen doğum ve köye, dedenin çiftliğine dönen torundur. İki hikâyede de oğul babasıyla ancak en sonunda, su kenarında barışır."
},
{
 a:{ad:"Bugün Aslında Dündü", es:["bugün aslında dündü","groundhog day"], yil:1993, tur:"fantastik komedi", yon:"Harold Ramis", oy:"Bill Murray"},
 b:{ad:"Kelebek Etkisi", es:["kelebek etkisi","the butterfly effect","butterfly effect"], yil:2004, tur:"bilimkurgu gerilim", yon:"Eric Bress & J. M. Gruber", oy:"Ashton Kutcher"},
 m:"Kasaba festivalini sunmaya giden huysuz hava durumu spikeri, aynı günü tekrar tekrar yaşamaya başlar. Önce keyfini çıkarır, sonra çıldırır, en sonunda piyano öğrenir. Ama günlüklerini okuyarak geçmişe dönmeyi de çözünce iş sarpa sarar: çocukluğundaki tek bir ânı değiştirdiğinde, bugün sevdiği herkes başka birine dönüşmektedir."
},
{
 a:{ad:"Whiplash", es:["whiplash"], yil:2014, tur:"müzik-dram", yon:"Damien Chazelle", oy:"Miles Teller"},
 b:{ad:"Siyah Kuğu", es:["siyah kuğu","black swan"], yil:2010, tur:"psikolojik gerilim", yon:"Darren Aronofsky", oy:"Natalie Portman"},
 m:"Konservatuvarın en hırslı öğrencisi, başrol için hem kusursuz hem de karanlık olması gerektiğini öğrenir; aynadaki yansıması ondan bağımsız gülümsemeye başlamıştır bile. Provalarda ise tempoyu tutturamayanlara sandalye fırlatan, 'acele mi ettin, geriden mi geldin?' diye fısıldayan bir hoca vardır. Sahneye eline kan bulaşmadan çıkamayacaktır — üstelik kendi kanı."
},
{
 a:{ad:"Sevginin Gücü", es:["sevginin gücü","leon","léon"], yil:1994, tur:"aksiyon-dram", yon:"Luc Besson", oy:"Jean Reno"},
 b:{ad:"Taksi Şoförü", es:["taksi şoförü","taxi driver"], yil:1976, tur:"psikolojik dram", yon:"Martin Scorsese", oy:"Robert De Niro"},
 m:"Uykusuz taksici, gece vardiyasında şehrin pisliğini seyrede seyrede bilenir; aynanın karşısında 'bana mı dedin?' provaları yapmaktadır. Yan dairede ise sütünü içip saksı çiçeğini sulayan sessiz bir tetikçi oturur. İkisinin de yolu, bataklıktan çekip çıkarmak istedikleri küçük bir kıza düşer — ve ikisi de bunun için silahlanır."
},
{
 a:{ad:"Prestij", es:["prestij","the prestige","prestige"], yil:2006, tur:"gizem", yon:"Christopher Nolan", oy:"Hugh Jackman"},
 b:{ad:"Amadeus", es:["amadeus"], yil:1984, tur:"dönem dramı", yon:"Miloš Forman", oy:"F. Murray Abraham"},
 m:"Saray bestecisi, Tanrı'nın kendi yerine o hayta gence ses verdiğine inanıp onu bitirmeye and içer. Sahne büyücüsü ise rakibinin ışınlanma numarasının sırrını çözmek için hayatını — hatta hayatlarını — feda eder. İkisi de aynı hastalıktan muzdariptir: alkışın başkasına gitmesi."
},
{
 a:{ad:"Yukarı Bak", es:["yukarı bak","up"], yil:2009, tur:"animasyon", yon:"Pixar (Pete Docter)", oy:"—"},
 b:{ad:"Gran Torino", es:["gran torino"], yil:2008, tur:"dram", yon:"Clint Eastwood", oy:"Clint Eastwood"},
 m:"Karısını kaybetmiş aksi ihtiyar, kapısına dadanan çocuktan ve değişen mahalleden bıkmıştır. Kimine göre çözüm, verandada tüfekle oturup 'çimlerimden defol' demektir; kimine göre evi binlerce balona bağlayıp şelalenin yolunu tutmak. İki hâlde de yolculuğun sonunda o çocuk, ihtiyarın dünyadaki en kıymetlisi olur."
},
{
 a:{ad:"Dövüş Kulübü", es:["dövüş kulübü","fight club"], yil:1999, tur:"psikolojik dram", yon:"David Fincher", oy:"Edward Norton"},
 b:{ad:"Sapık", es:["sapık","psycho"], yil:1960, tur:"korku-gerilim", yon:"Alfred Hitchcock", oy:"Anthony Perkins"},
 m:"Annesinin sözünden çıkamayan utangaç motel işletmecisi, duş perdesinin arkasında ne döndüğünü çok iyi bilir. Uykusuz beyaz yakalı ise yeni tanıştığı karizmatik sabun imalatçısıyla bodrumlarda gizli bir kulüp kurar; ilk kural bellidir. İkisinin de evinde, kimsenin yüzünü görmediği bir 'öteki' yaşamaktadır."
},
{
 a:{ad:"Jurassic Park", es:["jurassic park","jurassic"], yil:1993, tur:"macera", yon:"Steven Spielberg", oy:"Sam Neill"},
 b:{ad:"King Kong", es:["king kong"], yil:2005, tur:"macera", yon:"Peter Jackson", oy:"Naomi Watts"},
 m:"Bir film ekibi, haritalarda olmayan adaya dev bir yaratığı görüntülemeye gider; bir milyarder ise kendi adasındaki yaratıkları bilet kesip seyrettirmek için park kurar. İki planda da elektrikli çitler yetmez. Finalde biri elinde sarışın oyuncuyla gökdelene tırmanır, öbürü müze lobisinde 'insanlığın doğuşu' pankartının altında kükrer."
},
{
 a:{ad:"Rocky", es:["rocky"], yil:1976, tur:"spor dramı", yon:"John G. Avildsen", oy:"Sylvester Stallone"},
 b:{ad:"Gladyatör", es:["gladyatör","gladiator"], yil:2000, tur:"tarihî dram", yon:"Ridley Scott", oy:"Russell Crowe"},
 m:"Kalabalığın önüne, kaybedeceği baştan ilan edilmiş bir dövüş için çıkarılan adam aslında iki kişidir: biri kenar mahalleden çıkma, et kasalarına yumruk atarak çalışan babayiğit; öbürü ailesi katledilip köle pazarından geçmiş eski bir general. Biri kum arenasında 'eğlenmiyor musunuz?' diye haykırır, öbürü şafakta merdivenleri koşup kollarını havaya kaldırır."
},
{
 a:{ad:"Susuz Yaz", es:["susuz yaz"], yil:1963, tur:"dram", yon:"Metin Erksan", oy:"Erol Taş"},
 b:{ad:"Kan Dökülecek", es:["kan dökülecek","there will be blood"], yil:2007, tur:"dram", yon:"Paul Thomas Anderson", oy:"Daniel Day-Lewis"},
 m:"Toprağın altından çıkan şey birinde su, öbüründe petroldür; ikisi de bir adamın gözünü karartmaya yeter. Biri kaynağın başını tutup suyu köylüden ve öz kardeşinden keser; öbürü kuyudan kuyuya yürüyüp sonunda 'senin payına düşeni ben içerim' diyecek kadar ileri gider. İkisi de her şeyi kazanır ve herkesi kaybeder."
},
{
 a:{ad:"Zindan Adası", es:["zindan adası","shutter island"], yil:2010, tur:"psikolojik gerilim", yon:"Martin Scorsese", oy:"Leonardo DiCaprio"},
 b:{ad:"Akıl Oyunları", es:["akıl oyunları","a beautiful mind","beautiful mind"], yil:2001, tur:"biyografik dram", yon:"Ron Howard", oy:"Russell Crowe"},
 m:"Dâhi matematikçi, Soğuk Savaş şifrelerini kırmak için gizli servise çalışmaktadır; federal şerif ise adadaki akıl hastanesinden kaybolan hastanın izini sürmektedir. İkisinin de soruşturması aynı gerçeğe çıkar: peşinde oldukları komplonun içindeki bazı insanlar, aslında hiç var olmamıştır."
},
{
 a:{ad:"Ayla", es:["ayla"], yil:2017, tur:"savaş dramı", yon:"Can Ulkay", oy:"İsmail Hacıoğlu"},
 b:{ad:"E.T.", es:["e.t.","et","e.t. the extra-terrestrial"], yil:1982, tur:"bilimkurgu", yon:"Steven Spielberg", oy:"Henry Thomas"},
 m:"Savaşın ortasında bir asker, enkazın içinde donmak üzere olan küçük bir kızı bulup birliğine getirir; banliyödeki çocuklar ise bahçede buldukları küçük yaratığı dolapta, oyuncakların arasında saklar. İki misafir de dilini bilmedikleri bir dünyaya sığınmıştır ve iki hikâye de aynı cümleye çıkar: 'evine dön.' Ayrılık sahnesinde ağlamayan varsa taş kalplidir."
},
{
 a:{ad:"Casablanca", es:["casablanca"], yil:1942, tur:"romantik dram", yon:"Michael Curtiz", oy:"Humphrey Bogart"},
 b:{ad:"La La Land", es:["la la land","lalaland"], yil:2016, tur:"müzikal", yon:"Damien Chazelle", oy:"Ryan Gosling"},
 m:"Biri Paris'i hatırlar, öbürü Paris'i hayal eder. İkisinde de bir piyanonun başında hep aynı eski şarkı çalınır ve adam, sevdiği kadını başka bir hayata uğurlar. Yıllar sonra kadın, kocasının koluna girmiş hâlde o kapıdan içeri girer; adam piyaniste 'çal' der — ya da hiçbir şey demez, yalnızca başıyla selamlar."
}
]
};
